### ISSUE TITLE
Error after migrating from v97.0.0 to v98.0.0

### ISSUE THREAD

**Issue by claudiu-muresan-pfa** [mightyiam/eslint-config-love#1890]
Have below error when running `yarn eslint --fix .` in my project:
```
Oops! Something went wrong! :(

ESLint: 9.14.0

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/claudiumuresan/Projects/WaylayIO-Private/waylay-js/node_modules/eslint-config-love/lib/rules/eslint-comments.js' imported from /Users/claudiumuresan/Projects/WaylayIO-Private/waylay-js/node_modules/eslint-config-love/lib/rules.js
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:327:11)
    at moduleResolve (node:internal/modules/esm/resolve:946:10)
    at defaultResolve (node:internal/modules/esm/resolve:1132:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36)
error Command failed with exit code 2.
```

The eslint config is the following:
```
import love from "eslint-config-love";
import prettier from "eslint-config-prettier";
import path from "node:path";
import { fileURLToPath } from "node:url";
import js from "@eslint/js";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const compat = new FlatCompat({
    baseDirectory: __dirname,
    recommendedConfig: js.configs.recommended,
    allConfig: js.configs.all
});

export default [
    {
        ignores: [
            "**/rollup.config.js",
            "**/cypress.config.ts",
            "**/eslint.config.mjs",
            "**/cypress/",
            "**/coverage/",
            "**/dist/",
            "**/docs-dist/"
        ]
    },
    love,
    prettier,
    ...compat.extends(
        "eslint:recommended",
        "plugin:@typescript-eslint/recommended-type-checked",
        "plugin:@typescript-eslint/stylistic-type-checked",
        "plugin:prettier/recommended"
    ),
    {
        languageOptions: {
            ecmaVersion: 2019,
            sourceType: "script",

            parserOptions: {
                project: ["./tsconfig.json"]
            }
        },
        rules: {
            "@typescript-eslint/no-magic-numbers": "off",
            "@typescript-eslint/no-unused-vars": "off",
            "@typescript-eslint/prefer-destructuring": "off",
            "@typescript-eslint/no-unsafe-assignment": "off",
            "@typescript-eslint/no-unsafe-member-access": "off",
            "@typescript-eslint/no-explicit-any": "off",
            "@typescript-eslint/no-unsafe-argument": "off",
            "@typescript-eslint/no-unsafe-call": "off",
            "@typescript-eslint/class-methods-use-this": "off",
            "@typescript-eslint/max-params": ["error", { max: 6 }],
            "@typescript-eslint/no-unnecessary-condition": "off",
            "@typescript-eslint/no-unsafe-return": "off",
            "@typescript-eslint/no-require-imports": "off",
            "@typescript-eslint/no-redundant-type-constituents": "off",
            "@typescript-eslint/no-empty-function": "off",
            "@typescript-eslint/init-declarations": "off",
            "@typescript-eslint/only-throw-error": "off",
            "@typescript-eslint/no-unsafe-function-type": "off",
            "@typescript-eslint/no-unsafe-declaration-merging": "off",
            "@typescript-eslint/unbound-method": "off",
            "@typescript-eslint/no-empty-object-type": "off",
            "@typescript-eslint/require-await": "off",
            "@typescript-eslint/strict-boolean-expressions": "off",
            "@typescript-eslint/explicit-function-return-type": "off",
            "@typescript-eslint/restrict-template-expressions": "off",
            "@typescript-eslint/prefer-nullish-coalescing": "off",
            "@typescript-eslint/prefer-optional-chain": "off",
            "@typescript-eslint/adjacent-overload-signatures": "off",
            "@typescript-eslint/promise-function-async": "off",
            "@typescript-eslint/ban-types": "off",
            "@typescript-eslint/no-floating-promises": "off",
            "@typescript-eslint/no-misused-promises": "off",
            "@typescript-eslint/no-non-null-assertion": "off",
            "@typescript-eslint/no-empty-interface": "off",
            "@typescript-eslint/consistent-type-imports": "off",
            "@typescript-eslint/no-deprecated": "off",

            "import/no-extraneous-dependencies": ["error", {
                devDependencies: ["test/**/*.ts", "integration/**/*.ts", "rollup.config.js"],
            }],

            "prettier/prettier": "error"
        }
}];
```

**Comment by mightyiam** [comment]
Sorry!
